#cloud-config
# This file is used by the VM at startup to automatically install Docker.

package_update: true
package_upgrade: true

packages:
  - curl
  - git

runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh

  # Install the Docker Compose V2 plugin
  - apt-get install -y docker-compose-plugin docker-buildx-plugin

  - usermod -aG docker azureuser

  - systemctl enable docker
  - systemctl start docker
