name: CI/CD Pipeline

# STEP 1: WHEN THIS PIPELINE RUNS
# Runs automatically whenever code is pushed to the develop or main branch.
on:
  push:
    branches:
      - develop
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
     # STEP 2: Get the latest code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # STEP 3: Log in to Docker Hub using secrets (never hardcode passwords)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # STEP 4: Create a short, unique tag from the Git commit SHA
      # Example: a3f9c21 instead of "latest"
      - name: Set image tag
        id: vars
        run: echo "sha_tag=$(echo $GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      # STEP 5: Build and push the BACKEND image
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            YOUR_DOCKERHUB_USERNAME/formflow-backend:${{ steps.vars.outputs.sha_tag }}
            YOUR_DOCKERHUB_USERNAME/formflow-backend:latest

      # STEP 6: Build and push the FRONTEND image
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            YOUR_DOCKERHUB_USERNAME/formflow-frontend:${{ steps.vars.outputs.sha_tag }}
            YOUR_DOCKERHUB_USERNAME/formflow-frontend:latest
deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
       #STEP 7: SSH into the Azure VM and redeploy using the new images
       - name: Deploy to Azure VM
         uses: appleboy/ssh-action@v1.0.0
         with:
           host: ${{ secrets.VM_HOST }}
           username: ${{ secrets.VM_USERNAME }}
           key: ${{ secrets.VM_SSH_KEY }}
           script: |
             cd /home/YOUR_VM_USERNAME/3-tier-dockerized-application
             docker compose pull
             docker compose up -d
                     